### ISSUE TITLE
Not really an issue

### ISSUE THREAD

**Issue by paulofaria** [PureSwift/SwiftFoundation#6]
Hey man! I really liked this. I saw you forked my HTTP Server / Web Framework. Really enjoying this pure swift experiment. I see you have done a lot of similar work like, regular expressions, base64, etc.. This is really cool. I'm going to take a closer look later. It would be very interesting to have a centralized solution for this new "problem" of having code that runs on Linux as well. Willing to contribute to this!

Talking about another matter that it's very important, as well. I think it was you who did a post about using pure swift frameworks in command line applications by faking a bundle, was it? Is there another way? Swift not having a stable ABI sucks, and they (apple) have no clue when it'll happen.

Having some sort of package management like NPM and the likes would be awesome too, because the current ones (cocoapod, carthage) aren't doing the trick. Will they ever?

Sorry for using an issue to contact here. Is there a better way to contact another user in github?

**Comment by colemancda** [comment]
@paulofaria Cool! So I use Carthage and it works really well for this. And yes, that post is [here](http://colemancda.github.io/programming/2015/02/12/embedded-swift-frameworks-osx-command-line-tools/). Please contact me on [Gitter](https://gitter.im/PureSwift/SwiftFoundation) it works really great for these kind of projects. My code is heavily unit-tested since I intend to use this in a production environment once Swift is open sourced.
